<?php

use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "api" middleware group. Enjoy building your API!
|
*/

Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user();
});

// route/api.php

use App\tbitems;

Route::get('/data',function(){
	
	$items = tbitems::all()->toJson();
	return response($items,200)->header('Content-Type', 'application/json', 'Access-Control-Allow-Origin' , '*');

});

Route::post('/data/create',function(Request $req){
	
    //data request from client side should be looked like this
	//{"name":"a"}
	//[{"name":"b"},{"name":"c"}]

	$data = $req->json()->all();

	$item = new tbitems();

	$item->name = $data['name'];

	$item->save();

	return response(($result === true ? 'succeed':'failed'),200)->header('Content-Type', 'application/json', 'Access-Control-Allow-Origin' , '*', 'Access-Control-Allow-Methods', 'POST, GET, OPTIONS, PUT');

});


Route::put('/data/update',function(Request $req){
	
    $data = $req->json()->all();

	$item = tbitems::find($data['id']);

	$item->name = $data['name'];

    $item->save();

	return response(($result === true ? 'succeed':'failed'),200)->header('Content-Type', 'application/json');

});


Route::delete('/data/delete', function(Request $req){
	
    $data = $req->json()->all();

	$result = tbitems::destroy($data['id']);

	return response(($result === true ? 'succeed':'failed'),200)->header('Content-Type', 'application/json', 'Access-Control-Allow-Origin' , '*', 'Access-Control-Allow-Methods', 'POST, GET, OPTIONS, PUT');

});#autogenerated
Route::resource('tbitems', 'Api\TbitemsController', ['except' => ['create', 'edit']]);
#endautogenerated